services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    #ports: - Если нужно подключиться к этой базе данных откуда-то ещё
    #  - 5432:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}

  muslib:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: "./"
      dockerfile: 'Dockerfile'
    ports:
      - ${LIBRARY_SERVICE_PORT}:${LIBRARY_SERVICE_PORT}
    environment:
      LIBRARY_SERVICE_PORT: ${LIBRARY_SERVICE_PORT}
      LIBRARY_SERVICE_LOG_LEVEL: ${LIBRARY_SERVICE_LOG_LEVEL}
      MUSIC_INFO_SERVICE_ADDRESS: ${MUSIC_INFO_SERVICE_ADDRESS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_TIMEZONE: ${POSTGRES_TIMEZONE}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}

